version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: jewelry_shop_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # для сохранности данных

  web:
    build: .
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:  # volume для сохранности данных PostgreSQL
