version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: weirdlyggg
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jewelry_shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: